---
version: "3.9"

services:
  api:
    container_name: api_container
    build: ./api
    command:
      bash -c 
      "
      python3 manage.py runserver 0.0.0.0:8000
      "
    ports:
      - 8000:8000
    networks:
      opc_network:
        ipv4_address: 10.0.0.2
    volumes:
      - ./api:/code

networks:
  opc_network:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.0.0.0/24
