---
version: "3.9"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mvlab
      POSTGRES_PASSWORD: z1x2c3
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
      TZ: Europe/Minsk
    volumes:
      - postgres_opc:/data/postgres
    ports:
      - "5432:5432"
    networks:
      opc_network:
        ipv4_address: 10.0.0.3

  api:
    container_name: api_container
    build: ./api
    command:
      bash -c 
      "
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      python3 manage.py runserver 0.0.0.0:8000
      "
    ports:
      - 8000:8000
    networks:
      opc_network:
        ipv4_address: 10.0.0.2
    volumes:
      - ./api:/code

  opc:
    container_name: opc_container
    build: ./api
    command:
      bash -c
      "
      python3 background_worker/main.py
      "
    networks:
      opc_network:
        ipv4_address: 10.0.0.4
    volumes:
      - ./api:/code


networks:
  opc_network:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        - subnet: 10.0.0.0/24

volumes:
  postgres_opc: