# Generated by Django 4.1.5 on 2023-02-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('driver', models.CharField(max_length=30)),
                ('ip_addres', models.CharField(max_length=17)),
                ('port', models.IntegerField(default=502)),
                ('slot', models.IntegerField(null=True)),
                ('rack', models.IntegerField(null=True)),
                ('switcher', models.BooleanField(default=False)),
                ('status_conncection', models.BooleanField(default=False)),
                ('status_proccese', models.BooleanField(default=False)),
            ],
        ),
    ]
